export const surpriseMePrompts = [
  "A smiling octopus playing the guitar underwater.",
  "A majestic castle floating in the clouds.",
  "An astronaut riding a unicorn on the moon.",
  "A futuristic cityscape with flying cars and holographic billboards.",
  "A serene forest with bioluminescent plants illuminating the night.",
  "A giant mechanical dragonfly soaring over a steampunk city.",
  "An abstract representation of human emotions through colors and shapes.",
  "A cyberpunk hacker merging with the digital world.",
  "An ancient library filled with magical books and artifacts.",
  "A family of friendly aliens having a picnic in a lush alien landscape.",
  "A beautiful mermaid exploring an underwater coral garden.",
  "A living treehouse inhabited by friendly woodland creatures.",
  "A time-traveling train journeying through different historical eras.",
  "A cosmic ballet of celestial bodies and galaxies colliding.",
  "A futuristic city engulfed in a neon aurora borealis.",
  "An enchanted waterfall that grants wishes to those who bathe in its waters.",
  "A surreal landscape with floating islands and upside-down mountains.",
  "A group of robots engaged in a harmonious dance routine.",
  "A surreal chessboard where the pieces come to life and battle.",
  "A fantastical circus with mythical creatures as performers.",
  "A giant talking sunflower with a cheerful personality.",
  "A steampunk airship race through the clouds.",
  "A massive sea creature emerging from the depths of the ocean.",
  "A wizard's workshop filled with magical potions and spellbooks.",
  "A time-traveling archaeologist discovering ancient alien ruins.",
  "An otherworldly ice cream parlor with flavors from different planets.",
  "A floating island inhabited by miniature people and creatures.",
  "A living, breathing city powered by renewable energy sources.",
  "A swarm of fireflies creating a breathtaking light show in the night sky.",
  "A group of friendly dinosaurs tending to a futuristic farm.",
  "An enchanted labyrinth guarded by mythical creatures.",
  "A secret garden filled with rare and mystical plants.",
  "A group of superheroes and villains engaged in an epic battle.",
  "A peaceful underwater utopia where humans and marine life coexist.",
  "A whimsical carnival with rides powered by imagination.",
  "A hidden portal leading to parallel dimensions.",
  "A giant underwater library filled with ancient knowledge.",
  "A futuristic underwater city with glass domes and underwater transportation.",
  "A rainbow-colored waterfall flowing into a bottomless abyss.",
  "A group of animals forming a band and playing instruments.",
  "A magical forest where every tree has a unique pattern of glowing leaves.",
  "A steampunk-style time machine ready for its next journey.",
  "A colony of friendly extraterrestrial creatures living on a distant planet.",
  "A mythical phoenix rising from its ashes in a blaze of vibrant colors.",
  "A celestial concert with planets and stars as musical instruments.",
  "A floating marketplace with stalls run by fairytale creatures.",
  "A living constellation of zodiac signs, each personified with unique traits.",
  "A futuristic underwater research station studying marine life.",
  "A journey through a series of mesmerizing fractal landscapes.",
  "A cosmic ballet of colorful nebulae swirling and dancing in space."
];